apiVersion: apps/v1  # Corrected
kind: Deployment
metadata: 
  name: reg-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register
        image: yashdocker39/register
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service  # Corrected
metadata:
  name: reg-services
spec:
  selector:
    app: register
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: LoadBalancer